# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# BetterConfig Properties
mod_version=2.8.0
maven_group=dev.xpple
archives_base_name=betterconfig

# Minecraft properties
minecraft_version=26.3-rc-1
minecraft_dependency=>=26.3-rc.1 <26.4

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_api_version=0.160.3+26.3
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT

devauth_version=1.2.2

# Paper Properties
paper_api_version=26.3-pre-2.build.0-alpha
plugin_yml_paper_api_version=26.3
